version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/kotlin"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "org.flywaydb:flyway-core"
        versions:
          - "*"
      - dependency-name: "org.flywaydb:flyway-mysql"
        versions:
          - "*"
    groups:
      non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "uv"
    directory: "/python"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      dev:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      non-major:
        applies-to: version-updates
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/react"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      dev:
        applies-to: version-updates
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      non-major:
        applies-to: version-updates
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/kotlin"
      - "/python"
      - "/react"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/python"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker-compose"
    directories:
      - "/kotlin"
      - "/python"
      - "/php"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
