services:

  php:
    image: "php:8-apache"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
